_blog_index:
    path:     /{category}
    defaults: { _controller: MajesBlogBundle:Blog:index, category : null}

_blog_article:
    path:     /{category}/{url}
    defaults: { _controller: MajesBlogBundle:Blog:content}